# pytest.ini
[pytest]
filterwarnings =
    ignore:builtin type SwigPy.* has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning


